# Model Training

In [73]:
# importing required data and packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#modelling
from sklearn.metrics import mean_absolute_error, r2_score, median_absolute_error, mean_squared_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import Ridge, Lasso, LinearRegression
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [74]:
# importing the csv file as dataframe
try:
    df = pd.read_csv("data/preprocessed/preprocessed.csv")
except:
    df = pd.read_csv("preprocessed.csv")

In [75]:
df = df.drop(columns=['id'], axis=1)

In [76]:
df.head()

,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,accident_risk,speed_risk_band,high_curvature,lane_complexity,accident_density,poor_visibility
0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,0.13,low,0,0.12,0.333333,0
1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,0.35,low,1,3.96,0.000000,0
2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,0.30,medium,1,2.52,0.400000,0
3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,0.21,low,0,0.28,0.200000,0
4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,0.56,medium,0,0.58,0.500000,0

In [77]:
target = "accident_risk"

In [78]:
# --- PREPARING X AND Y VARIABLES---
X = df.drop(columns=[target], axis=1)
X.head()

,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,speed_risk_band,high_curvature,lane_complexity,accident_density,poor_visibility
0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,low,0,0.12,0.333333,0
1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,low,1,3.96,0.000000,0
2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,medium,1,2.52,0.400000,0
3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,low,0,0.28,0.200000,0
4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,medium,0,0.58,0.500000,0

In [79]:
X.head()

,road_type,num_lanes,curvature,speed_limit,lighting,weather,road_signs_present,public_road,time_of_day,holiday,school_season,num_reported_accidents,speed_risk_band,high_curvature,lane_complexity,accident_density,poor_visibility
0,urban,2,0.06,35,daylight,rainy,False,True,afternoon,False,True,1,low,0,0.12,0.333333,0
1,urban,4,0.99,35,daylight,clear,True,False,evening,True,True,0,low,1,3.96,0.000000,0
2,rural,4,0.63,70,dim,clear,False,True,morning,True,False,2,medium,1,2.52,0.400000,0
3,highway,4,0.07,35,dim,rainy,True,True,morning,False,False,1,low,0,0.28,0.200000,0
4,rural,1,0.58,60,daylight,foggy,False,False,evening,True,False,1,medium,0,0.58,0.500000,0

In [80]:
Y = df[target]
Y.head()

0    0.13
1    0.35
2    0.30
3    0.21
4    0.56
Name: accident_risk, dtype: float64

In [81]:
numerical_features = [
    "num_lanes",
    "curvature",
    "speed_limit",
    "lane_complexity"      # SAFE
]

categorical_features = [
    "road_type",
    "lighting",
    "weather",
    "time_of_day",
    "speed_risk_band"      # SAFE engineered category
]


boolean_features = [
    "road_signs_present",
    "public_road",
    "holiday",
    "school_season",
    "high_curvature",      # SAFE
    "poor_visibility"      # SAFE
]

In [82]:
df['school_season']

0          True
1          True
2         False
3         False
4         False
          ...
517749    False
517750    False
517751     True
517752     True
517753     True
Name: school_season, Length: 517754, dtype: bool

In [83]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

preprocessor = ColumnTransformer(
    transformers=[

        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore',sparse_output=False), categorical_features),
        ('bool', OneHotEncoder(handle_unknown='ignore',sparse_output=False), boolean_features)
    ]
)

In [84]:
preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['num_lanes', 'curvature', 'speed_limit',
                                  'lane_complexity']),
                                ('cat',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['road_type', 'lighting', 'weather',
                                  'time_of_day', 'speed_risk_band']),
                                ('bool',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['road_signs_present', 'public_road',
                                  'holiday', 'school_season', 'high_curvature',
                                  'poor_visibility'])])

In [85]:

X = preprocessor.fit_transform(X)

In [86]:
X.shape

(517754, 30)

In [87]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print("x_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train_shape", y_train.shape)
print("y_test shape:", y_test.shape)

x_train shape: (414203, 30)
X_test shape: (103551, 30)
y_train_shape (414203,)
y_test shape: (103551,)

In [88]:
# create an evaluate function to evaluate models
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mse)
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [89]:
models = {
    'linear_regression': LinearRegression(),
    'lasso_regression': Lasso(),
    'Ridge_regression': Ridge(),
    'KNN_regressor': KNeighborsRegressor(),
    'Decision_tree_regressor': DecisionTreeRegressor(),
    'Random_forest_regressor': RandomForestRegressor(),
    'XGB_regressor': XGBRegressor(),
    'cat_boost_regressor': CatBoostRegressor(),
    'Ada_boost_regressor': AdaBoostRegressor()
}

model_report = [] # to store model evaluation reports
r2_list = [] # to store r2 scores of different models

for i in range(len(models)):
    model = list(models.values())[i]
    model.fit(X_train, y_train)
    y_test_pred = model.predict(X_test)
    y_train_pred = model.predict(X_train)

    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    model_report.append(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    r2_list.append(model_test_r2)
    
    print('='*35)
    print('\n')

linear_regression
Model performance for Training set
- Root Mean Squared Error: 0.0627
- Mean Absolute Error: 0.0484
- R2 Score: 0.8583
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.0628
- Mean Absolute Error: 0.0485
- R2 Score: 0.8572
===================================


lasso_regression
Model performance for Training set
- Root Mean Squared Error: 0.1665
- Mean Absolute Error: 0.1330
- R2 Score: 0.0000
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.1662
- Mean Absolute Error: 0.1327
- R2 Score: -0.0000
===================================


Ridge_regression
Model performance for Training set
- Root Mean Squared Error: 0.0627
- Mean Absolute Error: 0.0484
- R2 Score: 0.8583
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.0628
- Mean Absolute Error: 0.0485
- R2 Score: 0.8572
===================================


KNN_regressor
Model performance for Training set
- Root Mean Squared Error: 0.0568
- Mean Absolute Error: 0.0440
- R2 Score: 0.8835
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.0699
- Mean Absolute Error: 0.0541
- R2 Score: 0.8229
===================================


Decision_tree_regressor
Model performance for Training set
- Root Mean Squared Error: 0.0176
- Mean Absolute Error: 0.0054
- R2 Score: 0.9888
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.0892
- Mean Absolute Error: 0.0687
- R2 Score: 0.7116
===================================


Random_forest_regressor
Model performance for Training set
- Root Mean Squared Error: 0.0285
- Mean Absolute Error: 0.0211
- R2 Score: 0.9707
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.0664
- Mean Absolute Error: 0.0513
- R2 Score: 0.8405
===================================


XGB_regressor
Model performance for Training set
- Root Mean Squared Error: 0.0604
- Mean Absolute Error: 0.0467
- R2 Score: 0.8682
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 0.0614
- Mean Absolute Error: 0.0475
- R2 Score: 0.8633
===================================


Learning rate set to 0.106096
0:	learn: 0.1517015	total: 293ms	remaining: 4m 52s
1:	learn: 0.1387634	total: 355ms	remaining: 2m 57s
2:	learn: 0.1273879	total: 417ms	remaining: 2m 18s
3:	learn: 0.1175348	total: 476ms	remaining: 1m 58s
4:	learn: 0.1089923	total: 538ms	remaining: 1m 47s
5:	learn: 0.1016707	total: 610ms	remaining: 1m 41s
6:	learn: 0.0953374	total: 671ms	remaining: 1m 35s
7:	learn: 0.0898778	total: 730ms	remaining: 1m 30s
8:	learn: 0.0852544	total: 790ms	remaining: 1m 26s
9:	learn: 0.0813856	total: 876ms	remaining: 1m 26s
10:	learn: 0.0780596	total: 930ms	remaining: 1m 23s
11:	learn: 0.0752444	total: 992ms	remaining: 1m 21s
12:	learn: 0.0729075	total: 1.06s	remaining: 1m 20s
13:	learn: 0.0709724	total: 1.13s	remaining: 1m 19s
14:	learn: 0.0693530	total: 1.2s	remaining: 1m 18s
15:	learn: 0.0680165	total: 1.26s	remaining: 1m 17s
16:	learn: 0.0669304	total: 1.42s	remaining: 1m 21s
17:	learn: 0.0660326	total: 1.51s	remaining: 1m 22s
18:	learn: 0.0653129	total: 1.58s	remaining: 1m 21s
19:	learn: 0.0647213	total: 1.64s	remaining: 1m 20s
20:	learn: 0.0642440	total: 1.71s	remaining: 1m 19s
21:	learn: 0.0638413	total: 1.77s	remaining: 1m 18s
22:	learn: 0.0635133	total: 1.84s	remaining: 1m 18s
23:	learn: 0.0632441	total: 1.91s	remaining: 1m 17s
24:	learn: 0.0630184	total: 1.96s	remaining: 1m 16s
25:	learn: 0.0628314	total: 2.03s	remaining: 1m 16s
26:	learn: 0.0626644	total: 2.1s	remaining: 1m 15s
27:	learn: 0.0625396	total: 2.17s	remaining: 1m 15s
28:	learn: 0.0624365	total: 2.24s	remaining: 1m 14s
29:	learn: 0.0623508	total: 2.4s	remaining: 1m 17s
30:	learn: 0.0622661	total: 2.53s	remaining: 1m 19s
31:	learn: 0.0622094	total: 2.6s	remaining: 1m 18s
32:	learn: 0.0621444	total: 2.67s	remaining: 1m 18s
33:	learn: 0.0620912	total: 2.73s	remaining: 1m 17s
34:	learn: 0.0620476	total: 2.79s	remaining: 1m 16s
35:	learn: 0.0620115	total: 2.85s	remaining: 1m 16s
36:	learn: 0.0619816	total: 2.92s	remaining: 1m 15s
37:	learn: 0.0619436	total: 2.99s	remaining: 1m 15s
38:	learn: 0.0619163	total: 3.04s	remaining: 1m 14s
39:	learn: 0.0618964	total: 3.11s	remaining: 1m 14s
40:	learn: 0.0618763	total: 3.18s	remaining: 1m 14s
41:	learn: 0.0618591	total: 3.25s	remaining: 1m 14s
42:	learn: 0.0618429	total: 3.31s	remaining: 1m 13s
43:	learn: 0.0618301	total: 3.37s	remaining: 1m 13s
44:	learn: 0.0618168	total: 3.43s	remaining: 1m 12s
45:	learn: 0.0618008	total: 3.5s	remaining: 1m 12s
46:	learn: 0.0617925	total: 3.55s	remaining: 1m 12s
47:	learn: 0.0617689	total: 3.61s	remaining: 1m 11s
48:	learn: 0.0617604	total: 3.66s	remaining: 1m 11s
49:	learn: 0.0617505	total: 3.73s	remaining: 1m 10s
50:	learn: 0.0617395	total: 3.79s	remaining: 1m 10s
51:	learn: 0.0617339	total: 3.85s	remaining: 1m 10s
52:	learn: 0.0617252	total: 3.92s	remaining: 1m 10s
53:	learn: 0.0617091	total: 3.98s	remaining: 1m 9s
54:	learn: 0.0617009	total: 4.04s	remaining: 1m 9s
55:	learn: 0.0616903	total: 4.11s	remaining: 1m 9s
56:	learn: 0.0616854	total: 4.18s	remaining: 1m 9s
57:	learn: 0.0616789	total: 4.25s	remaining: 1m 9s
58:	learn: 0.0616757	total: 4.31s	remaining: 1m 8s
59:	learn: 0.0616697	total: 4.36s	remaining: 1m 8s
60:	learn: 0.0616619	total: 4.42s	remaining: 1m 8s
61:	learn: 0.0616592	total: 4.49s	remaining: 1m 7s
62:	learn: 0.0616517	total: 4.55s	remaining: 1m 7s
63:	learn: 0.0616416	total: 4.6s	remaining: 1m 7s
64:	learn: 0.0616336	total: 4.67s	remaining: 1m 7s
65:	learn: 0.0616285	total: 4.74s	remaining: 1m 7s
66:	learn: 0.0616225	total: 4.8s	remaining: 1m 6s
67:	learn: 0.0616152	total: 4.86s	remaining: 1m 6s
68:	learn: 0.0616096	total: 4.93s	remaining: 1m 6s
69:	learn: 0.0616074	total: 5s	remaining: 1m 6s
70:	learn: 0.0616014	total: 5.07s	remaining: 1m 6s
71:	learn: 0.0615980	total: 5.13s	remaining: 1m 6s
72:	learn: 0.0615955	total: 5.21s	remaining: 1m 6s
73:	learn: 0.0615906	total: 5.28s	remaining: 1m 6s
74:	learn: 0.0615870	total: 5.35s	remaining: 1m 5s
75:	learn: 0.0615830	total: 5.41s	remaining: 1m 5s
76:	learn: 0.0615787	total: 5.49s	remaining: 1m 5s
77:	learn: 0.0615752	total: 5.56s	remaining: 1m 5s
78:	learn: 0.0615698	total: 5.63s	remaining: 1m 5s
79:	learn: 0.0615661	total: 5.69s	remaining: 1m 5s
80:	learn: 0.0615645	total: 5.76s	remaining: 1m 5s
81:	learn: 0.0615558	total: 5.84s	remaining: 1m 5s
82:	learn: 0.0615537	total: 5.9s	remaining: 1m 5s
83:	learn: 0.0615512	total: 5.96s	remaining: 1m 5s
84:	learn: 0.0615491	total: 6.02s	remaining: 1m 4s
85:	learn: 0.0615457	total: 6.14s	remaining: 1m 5s
86:	learn: 0.0615432	total: 6.2s	remaining: 1m 5s
87:	learn: 0.0615401	total: 6.27s	remaining: 1m 4s
88:	learn: 0.0615369	total: 6.34s	remaining: 1m 4s
89:	learn: 0.0615314	total: 6.4s	remaining: 1m 4s
90:	learn: 0.0615264	total: 6.47s	remaining: 1m 4s
91:	learn: 0.0615235	total: 6.55s	remaining: 1m 4s
92:	learn: 0.0615191	total: 6.62s	remaining: 1m 4s
93:	learn: 0.0615163	total: 6.68s	remaining: 1m 4s
94:	learn: 0.0615140	total: 6.77s	remaining: 1m 4s
95:	learn: 0.0615121	total: 6.84s	remaining: 1m 4s
96:	learn: 0.0615096	total: 6.91s	remaining: 1m 4s
97:	learn: 0.0615071	total: 6.99s	remaining: 1m 4s
98:	learn: 0.0615044	total: 7.06s	remaining: 1m 4s
99:	learn: 0.0615024	total: 7.12s	remaining: 1m 4s
100:	learn: 0.0614999	total: 7.19s	remaining: 1m 4s
101:	learn: 0.0614955	total: 7.25s	remaining: 1m 3s
102:	learn: 0.0614939	total: 7.33s	remaining: 1m 3s
103:	learn: 0.0614915	total: 7.41s	remaining: 1m 3s
104:	learn: 0.0614866	total: 7.47s	remaining: 1m 3s
105:	learn: 0.0614836	total: 7.54s	remaining: 1m 3s
106:	learn: 0.0614814	total: 7.61s	remaining: 1m 3s
107:	learn: 0.0614779	total: 7.68s	remaining: 1m 3s
108:	learn: 0.0614731	total: 7.75s	remaining: 1m 3s
109:	learn: 0.0614714	total: 7.83s	remaining: 1m 3s
110:	learn: 0.0614688	total: 7.9s	remaining: 1m 3s
111:	learn: 0.0614643	total: 7.96s	remaining: 1m 3s
112:	learn: 0.0614595	total: 8.03s	remaining: 1m 3s
113:	learn: 0.0614552	total: 8.1s	remaining: 1m 2s
114:	learn: 0.0614522	total: 8.19s	remaining: 1m 3s
115:	learn: 0.0614498	total: 8.26s	remaining: 1m 2s
116:	learn: 0.0614473	total: 8.33s	remaining: 1m 2s
117:	learn: 0.0614450	total: 8.4s	remaining: 1m 2s
118:	learn: 0.0614428	total: 8.46s	remaining: 1m 2s
119:	learn: 0.0614403	total: 8.53s	remaining: 1m 2s
120:	learn: 0.0614322	total: 8.61s	remaining: 1m 2s
121:	learn: 0.0614277	total: 8.7s	remaining: 1m 2s
122:	learn: 0.0614254	total: 8.76s	remaining: 1m 2s
123:	learn: 0.0614214	total: 8.83s	remaining: 1m 2s
124:	learn: 0.0614195	total: 8.9s	remaining: 1m 2s
125:	learn: 0.0614147	total: 8.99s	remaining: 1m 2s
126:	learn: 0.0614125	total: 9.06s	remaining: 1m 2s
127:	learn: 0.0614106	total: 9.12s	remaining: 1m 2s
128:	learn: 0.0614062	total: 9.2s	remaining: 1m 2s
129:	learn: 0.0614051	total: 9.26s	remaining: 1m 1s
130:	learn: 0.0614027	total: 9.33s	remaining: 1m 1s
131:	learn: 0.0614002	total: 9.39s	remaining: 1m 1s
132:	learn: 0.0613957	total: 9.47s	remaining: 1m 1s
133:	learn: 0.0613943	total: 9.54s	remaining: 1m 1s
134:	learn: 0.0613921	total: 9.6s	remaining: 1m 1s
135:	learn: 0.0613894	total: 9.67s	remaining: 1m 1s
136:	learn: 0.0613877	total: 9.75s	remaining: 1m 1s
137:	learn: 0.0613843	total: 9.83s	remaining: 1m 1s
138:	learn: 0.0613828	total: 9.88s	remaining: 1m 1s
139:	learn: 0.0613804	total: 9.95s	remaining: 1m 1s
140:	learn: 0.0613771	total: 10s	remaining: 1m 1s
141:	learn: 0.0613748	total: 10.1s	remaining: 1m
142:	learn: 0.0613730	total: 10.2s	remaining: 1m
143:	learn: 0.0613699	total: 10.2s	remaining: 1m
144:	learn: 0.0613686	total: 10.3s	remaining: 1m
145:	learn: 0.0613660	total: 10.4s	remaining: 1m
146:	learn: 0.0613647	total: 10.4s	remaining: 1m
147:	learn: 0.0613631	total: 10.5s	remaining: 1m
148:	learn: 0.0613610	total: 10.6s	remaining: 1m
149:	learn: 0.0613585	total: 10.6s	remaining: 1m
150:	learn: 0.0613564	total: 10.7s	remaining: 1m
151:	learn: 0.0613528	total: 10.8s	remaining: 1m
152:	learn: 0.0613502	total: 10.9s	remaining: 1m
153:	learn: 0.0613486	total: 10.9s	remaining: 1m
154:	learn: 0.0613473	total: 11s	remaining: 60s
155:	learn: 0.0613446	total: 11.1s	remaining: 59.9s
156:	learn: 0.0613421	total: 11.2s	remaining: 59.9s
157:	learn: 0.0613401	total: 11.2s	remaining: 59.8s
158:	learn: 0.0613379	total: 11.3s	remaining: 59.7s
159:	learn: 0.0613356	total: 11.3s	remaining: 59.6s
160:	learn: 0.0613345	total: 11.4s	remaining: 59.7s
161:	learn: 0.0613328	total: 11.5s	remaining: 59.5s
162:	learn: 0.0613319	total: 11.6s	remaining: 59.4s
163:	learn: 0.0613296	total: 11.6s	remaining: 59.3s
164:	learn: 0.0613281	total: 11.7s	remaining: 59.3s
165:	learn: 0.0613266	total: 11.8s	remaining: 59.2s
166:	learn: 0.0613255	total: 11.9s	remaining: 59.1s
167:	learn: 0.0613235	total: 11.9s	remaining: 59s
168:	learn: 0.0613220	total: 12s	remaining: 59s
169:	learn: 0.0613178	total: 12.1s	remaining: 58.9s
170:	learn: 0.0613152	total: 12.1s	remaining: 58.8s
171:	learn: 0.0613128	total: 12.2s	remaining: 58.8s
172:	learn: 0.0613105	total: 12.3s	remaining: 58.7s
173:	learn: 0.0613094	total: 12.4s	remaining: 58.7s
174:	learn: 0.0613084	total: 12.4s	remaining: 58.5s
175:	learn: 0.0613072	total: 12.5s	remaining: 58.4s
176:	learn: 0.0613059	total: 12.5s	remaining: 58.3s
177:	learn: 0.0613051	total: 12.6s	remaining: 58.3s
178:	learn: 0.0613026	total: 12.7s	remaining: 58.2s
179:	learn: 0.0613004	total: 12.7s	remaining: 58s
180:	learn: 0.0612984	total: 12.8s	remaining: 57.9s
181:	learn: 0.0612973	total: 12.9s	remaining: 57.9s
182:	learn: 0.0612955	total: 12.9s	remaining: 57.8s
183:	learn: 0.0612945	total: 13s	remaining: 57.7s
184:	learn: 0.0612922	total: 13.1s	remaining: 57.6s
185:	learn: 0.0612901	total: 13.2s	remaining: 57.6s
186:	learn: 0.0612895	total: 13.2s	remaining: 57.5s
187:	learn: 0.0612880	total: 13.3s	remaining: 57.4s
188:	learn: 0.0612864	total: 13.4s	remaining: 57.3s
189:	learn: 0.0612848	total: 13.4s	remaining: 57.2s
190:	learn: 0.0612828	total: 13.5s	remaining: 57.1s
191:	learn: 0.0612813	total: 13.6s	remaining: 57.1s
192:	learn: 0.0612795	total: 13.7s	remaining: 57.1s
193:	learn: 0.0612782	total: 13.7s	remaining: 57s
194:	learn: 0.0612760	total: 13.8s	remaining: 56.9s
195:	learn: 0.0612749	total: 13.9s	remaining: 56.9s
196:	learn: 0.0612733	total: 13.9s	remaining: 56.8s
197:	learn: 0.0612695	total: 14s	remaining: 56.8s
198:	learn: 0.0612675	total: 14.1s	remaining: 56.7s
199:	learn: 0.0612656	total: 14.2s	remaining: 56.7s
200:	learn: 0.0612630	total: 14.3s	remaining: 56.7s
201:	learn: 0.0612618	total: 14.3s	remaining: 56.6s
202:	learn: 0.0612603	total: 14.4s	remaining: 56.6s
203:	learn: 0.0612588	total: 14.5s	remaining: 56.5s
204:	learn: 0.0612574	total: 14.6s	remaining: 56.5s
205:	learn: 0.0612558	total: 14.6s	remaining: 56.4s
206:	learn: 0.0612548	total: 14.7s	remaining: 56.3s
207:	learn: 0.0612530	total: 14.8s	remaining: 56.5s
208:	learn: 0.0612520	total: 15s	remaining: 56.6s
209:	learn: 0.0612498	total: 15.2s	remaining: 57s
210:	learn: 0.0612487	total: 15.3s	remaining: 57.1s
211:	learn: 0.0612474	total: 15.4s	remaining: 57.2s
212:	learn: 0.0612460	total: 15.5s	remaining: 57.4s
213:	learn: 0.0612448	total: 15.7s	remaining: 57.6s
214:	learn: 0.0612436	total: 15.8s	remaining: 57.7s
215:	learn: 0.0612418	total: 15.9s	remaining: 57.6s
216:	learn: 0.0612396	total: 15.9s	remaining: 57.5s
217:	learn: 0.0612372	total: 16s	remaining: 57.5s
218:	learn: 0.0612351	total: 16.1s	remaining: 57.4s
219:	learn: 0.0612342	total: 16.2s	remaining: 57.3s
220:	learn: 0.0612326	total: 16.2s	remaining: 57.2s
221:	learn: 0.0612314	total: 16.3s	remaining: 57.1s
222:	learn: 0.0612303	total: 16.4s	remaining: 57s
223:	learn: 0.0612260	total: 16.4s	remaining: 56.9s
224:	learn: 0.0612246	total: 16.5s	remaining: 56.9s
225:	learn: 0.0612234	total: 16.6s	remaining: 56.8s
226:	learn: 0.0612223	total: 16.6s	remaining: 56.7s
227:	learn: 0.0612205	total: 16.7s	remaining: 56.6s
228:	learn: 0.0612185	total: 16.8s	remaining: 56.6s
229:	learn: 0.0612163	total: 16.9s	remaining: 56.5s
230:	learn: 0.0612149	total: 16.9s	remaining: 56.4s
231:	learn: 0.0612139	total: 17s	remaining: 56.3s
232:	learn: 0.0612125	total: 17.1s	remaining: 56.2s
233:	learn: 0.0612115	total: 17.2s	remaining: 56.2s
234:	learn: 0.0612105	total: 17.2s	remaining: 56.1s
235:	learn: 0.0612097	total: 17.3s	remaining: 56s
236:	learn: 0.0612085	total: 17.4s	remaining: 55.9s
237:	learn: 0.0612075	total: 17.4s	remaining: 55.8s
238:	learn: 0.0612062	total: 17.5s	remaining: 55.8s
239:	learn: 0.0612052	total: 17.6s	remaining: 55.8s
240:	learn: 0.0612027	total: 17.7s	remaining: 55.7s
241:	learn: 0.0612015	total: 17.9s	remaining: 56.1s
242:	learn: 0.0612007	total: 18s	remaining: 56.1s
243:	learn: 0.0611992	total: 18.1s	remaining: 56s
244:	learn: 0.0611979	total: 18.1s	remaining: 55.9s
245:	learn: 0.0611968	total: 18.2s	remaining: 55.8s
246:	learn: 0.0611954	total: 18.3s	remaining: 55.8s
247:	learn: 0.0611938	total: 18.3s	remaining: 55.6s
248:	learn: 0.0611930	total: 18.4s	remaining: 55.5s
249:	learn: 0.0611915	total: 18.5s	remaining: 55.5s
250:	learn: 0.0611890	total: 18.6s	remaining: 55.4s
251:	learn: 0.0611879	total: 18.6s	remaining: 55.3s
252:	learn: 0.0611863	total: 18.7s	remaining: 55.2s
253:	learn: 0.0611844	total: 18.8s	remaining: 55.2s
254:	learn: 0.0611835	total: 18.8s	remaining: 55s
255:	learn: 0.0611820	total: 18.9s	remaining: 55s
256:	learn: 0.0611813	total: 19s	remaining: 54.9s
257:	learn: 0.0611799	total: 19.1s	remaining: 54.8s
258:	learn: 0.0611787	total: 19.1s	remaining: 54.7s
259:	learn: 0.0611776	total: 19.2s	remaining: 54.6s
260:	learn: 0.0611762	total: 19.3s	remaining: 54.7s
261:	learn: 0.0611752	total: 19.4s	remaining: 54.6s
262:	learn: 0.0611739	total: 19.4s	remaining: 54.5s
263:	learn: 0.0611706	total: 19.5s	remaining: 54.4s
264:	learn: 0.0611691	total: 19.6s	remaining: 54.3s
265:	learn: 0.0611684	total: 19.7s	remaining: 54.2s
266:	learn: 0.0611666	total: 19.7s	remaining: 54.2s
267:	learn: 0.0611654	total: 19.8s	remaining: 54.1s
268:	learn: 0.0611620	total: 19.9s	remaining: 54s
269:	learn: 0.0611604	total: 20s	remaining: 53.9s
270:	learn: 0.0611593	total: 20s	remaining: 53.9s
271:	learn: 0.0611581	total: 20.1s	remaining: 53.8s
272:	learn: 0.0611566	total: 20.2s	remaining: 53.7s
273:	learn: 0.0611556	total: 20.2s	remaining: 53.6s
274:	learn: 0.0611546	total: 20.3s	remaining: 53.5s
275:	learn: 0.0611537	total: 20.4s	remaining: 53.5s
276:	learn: 0.0611525	total: 20.5s	remaining: 53.4s
277:	learn: 0.0611513	total: 20.5s	remaining: 53.3s
278:	learn: 0.0611499	total: 20.6s	remaining: 53.2s
279:	learn: 0.0611476	total: 20.7s	remaining: 53.1s
280:	learn: 0.0611457	total: 20.7s	remaining: 53.1s
281:	learn: 0.0611446	total: 20.8s	remaining: 53s
282:	learn: 0.0611432	total: 20.9s	remaining: 52.9s
283:	learn: 0.0611423	total: 21s	remaining: 52.8s
284:	learn: 0.0611413	total: 21s	remaining: 52.7s
285:	learn: 0.0611393	total: 21.1s	remaining: 52.7s
286:	learn: 0.0611383	total: 21.2s	remaining: 52.7s
287:	learn: 0.0611365	total: 21.3s	remaining: 52.6s
288:	learn: 0.0611352	total: 21.3s	remaining: 52.5s
289:	learn: 0.0611338	total: 21.4s	remaining: 52.4s
290:	learn: 0.0611330	total: 21.5s	remaining: 52.4s
291:	learn: 0.0611318	total: 21.6s	remaining: 52.3s
292:	learn: 0.0611309	total: 21.6s	remaining: 52.2s
293:	learn: 0.0611298	total: 21.7s	remaining: 52.1s
294:	learn: 0.0611289	total: 21.8s	remaining: 52s
295:	learn: 0.0611280	total: 21.8s	remaining: 51.9s
296:	learn: 0.0611268	total: 21.9s	remaining: 51.9s
297:	learn: 0.0611254	total: 22s	remaining: 51.8s
298:	learn: 0.0611244	total: 22.1s	remaining: 51.7s
299:	learn: 0.0611234	total: 22.1s	remaining: 51.6s
300:	learn: 0.0611224	total: 22.2s	remaining: 51.5s
301:	learn: 0.0611211	total: 22.3s	remaining: 51.4s
302:	learn: 0.0611201	total: 22.3s	remaining: 51.4s
303:	learn: 0.0611187	total: 22.4s	remaining: 51.3s
304:	learn: 0.0611176	total: 22.5s	remaining: 51.2s
305:	learn: 0.0611151	total: 22.5s	remaining: 51.1s
306:	learn: 0.0611125	total: 22.6s	remaining: 51s
307:	learn: 0.0611114	total: 22.7s	remaining: 51s
308:	learn: 0.0611107	total: 22.8s	remaining: 51s
309:	learn: 0.0611096	total: 22.9s	remaining: 50.9s
310:	learn: 0.0611088	total: 22.9s	remaining: 50.8s
311:	learn: 0.0611079	total: 23s	remaining: 50.7s
312:	learn: 0.0611072	total: 23.1s	remaining: 50.7s
313:	learn: 0.0611061	total: 23.2s	remaining: 50.6s
314:	learn: 0.0611048	total: 23.2s	remaining: 50.5s
315:	learn: 0.0611035	total: 23.3s	remaining: 50.4s
316:	learn: 0.0611026	total: 23.4s	remaining: 50.3s
317:	learn: 0.0611018	total: 23.4s	remaining: 50.2s
318:	learn: 0.0611003	total: 23.5s	remaining: 50.2s
319:	learn: 0.0610991	total: 23.6s	remaining: 50.1s
320:	learn: 0.0610980	total: 23.6s	remaining: 50s
321:	learn: 0.0610972	total: 23.7s	remaining: 49.9s
322:	learn: 0.0610962	total: 23.8s	remaining: 49.8s
323:	learn: 0.0610951	total: 23.9s	remaining: 49.8s
324:	learn: 0.0610941	total: 23.9s	remaining: 49.7s
325:	learn: 0.0610935	total: 24s	remaining: 49.6s
326:	learn: 0.0610929	total: 24.1s	remaining: 49.5s
327:	learn: 0.0610923	total: 24.1s	remaining: 49.4s
328:	learn: 0.0610916	total: 24.2s	remaining: 49.4s
329:	learn: 0.0610906	total: 24.3s	remaining: 49.3s
330:	learn: 0.0610896	total: 24.4s	remaining: 49.3s
331:	learn: 0.0610888	total: 24.4s	remaining: 49.2s
332:	learn: 0.0610867	total: 24.5s	remaining: 49.1s
333:	learn: 0.0610853	total: 24.6s	remaining: 49s
334:	learn: 0.0610843	total: 24.6s	remaining: 48.9s
335:	learn: 0.0610832	total: 24.7s	remaining: 48.9s
336:	learn: 0.0610825	total: 24.8s	remaining: 48.8s
337:	learn: 0.0610815	total: 24.9s	remaining: 48.7s
338:	learn: 0.0610802	total: 24.9s	remaining: 48.6s
339:	learn: 0.0610793	total: 25s	remaining: 48.6s
340:	learn: 0.0610781	total: 25.1s	remaining: 48.5s
341:	learn: 0.0610769	total: 25.2s	remaining: 48.4s
342:	learn: 0.0610740	total: 25.2s	remaining: 48.3s
343:	learn: 0.0610728	total: 25.3s	remaining: 48.3s

In [1]:
# result dataframe
result_df = pd.DataFrame({'Model':model_report, 'R2_score':r2_list, "rmse": })
result_df

SyntaxError: invalid syntax (1228500719.py, line 2)